FROM ${AIRFLOW_IMAGE_NAME:-apache/airflow:2.9.1-python3.11}

USER root

RUN apt-get update \
    && apt-get install -y --no-install-recommends openjdk-17-jdk-headless \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY docker/requirements.txt /requirements.txt

RUN pip install --no-cache-dir -r /requirements.txt

USER airflow
